# Generated by Django 3.2.7 on 2021-10-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mayoralties',
            fields=[
                ('mayoralty_id', models.AutoField(primary_key=True, serialize=False)),
                ('mayoralty_name', models.CharField(max_length=100)),
                ('mayoralty_shape', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetrobusTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('vehicle_id', models.PositiveSmallIntegerField()),
                ('vehicle_label', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('geographical_point', models.CharField(max_length=45)),
                ('trip_route_id', models.PositiveSmallIntegerField()),
                ('mayoralty_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pipeline.mayoralties')),
            ],
        ),
    ]
