# Generated by Django 3.2.7 on 2021-10-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrobustracking',
            name='mayotalty_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metrobustracking',
            name='mayoralty_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Mayoralties',
        ),
    ]
