# Generated by Django 3.2.7 on 2021-10-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20211003_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrobustracking',
            old_name='geographical_point',
            new_name='geographic_point',
        ),
    ]
