# Generated by Django 3.2.7 on 2021-10-04 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_alter_metrobustracking_trip_route_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrobustracking',
            old_name='mayotalty_name',
            new_name='mayoralty_name',
        ),
    ]
